---
title: "Green space benefits during lockdown 1"
output: html_notebook
bibliography: references.bib
---

```{r}
library(tidyverse)
```

*Data from [@poortinga2021] ([article here](https://www.sciencedirect.com/science/article/pii/S0169204621000554?via%3Dihub#s0090))*

*Green space access and subjective wellbeing*

```{r}
# sysfonts::font_add_google("Roboto", "robo")
# sysfonts::font_add_google("Roboto Slab", "slab")
# showtext::showtext_auto()
#showtext::showtext_opts(dpi = 300)

# copy data from descriptive stats in the paper (Table. 1)
gs_wellbeing <- tribble(
  ~garden, ~date, ~mean_response,
  "yes", "peak", 2.79, 
  "yes", "post-peak", 2.96 ,
  "no", "peak", 2.55,
  "no", "post-peak", 2.56
)

p <- ggplot(gs_wellbeing,
       aes(date, mean_response,
           colour = garden)) +
  geom_point(size = 5) +
  geom_path(aes(group = garden),
            position = "identity") +
  scale_y_continuous(
    
    # Features of the first axis
    name = "First Axis",
    
    # create a secondary dummy axis 
    # (to edit later in Affinity designer to add the qualiative repsonses the
    # scores correspond to)
    sec.axis = sec_axis( trans=~.*10, name="Second Axis"),
    limits = c(0,3)
  ) #+
  
  #bbplot::bbc_style()


ggsave("plot.svg")
```
```{r}
sysfonts::font_add_google("Lato", "Lato")
```


```{r fig.asp = 0.8, fig.width = 5, out.width = "100%"}
explanatory_theme_1 <- function(base_text_size = 12){
  
  
  grid_line_colour <- "grey"
  text_colour <- "black"
  background_colour <- "grey98"
  
  
  ggplot2::theme_bw(base_size = base_text_size) %+replace%
  
  ggplot2::theme(
    
    # format text
    text = ggplot2::element_text(family = "Lato"),
    plot.title = ggplot2::element_text(hjust = 0,
                                       size = ggplot2::rel(1.5)),
    plot.subtitle = ggplot2::element_text(hjust = 0,
                                          size = ggplot2::rel(1.25)),
    plot.caption = ggplot2::element_text(size = ggplot2::rel(0.8), 
                                         hjust = 0),
    
    # format legend
    legend.position = "top",
    legend.background = ggplot2::element_blank(),
    legend.title = ggplot2::element_blank(),
    legend.text = ggplot2::element_text(size = ggplot2::rel(0.8)),
    
    # format axis
    axis.text = ggplot2::element_text(size = rel(1)),
    axis.title.x = ggplot2::element_text(size = rel(1.1)),
    axis.title.y = ggplot2::element_blank(),
    axis.line.y = ggplot2::element_blank(),
    axis.line.x = ggplot2::element_blank(),
    # axis.line.x = ggplot2::element_line(colour = "black", size = 1),
    axis.ticks.x = ggplot2::element_line(colour = grid_line_colour, size = 1),
    axis.ticks.y = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_text(margin=ggplot2::margin(t = 1, b = 10)),
    
    # format plot gridlines
    panel.grid.minor = ggplot2::element_blank(),
    panel.grid.major.x = ggplot2::element_blank(),
    panel.grid.major.y = ggplot2::element_line(colour = grid_line_colour),
    
    # format plot background
    panel.background = ggplot2::element_blank(),
    
    # format overall background (i.e. background behind the entire figure
    # including the plot, titles etc.)
    plot.background = element_rect(fill = background_colour,
                                   colour = NA),
    
    # facet labels background
    strip.background = ggplot2::element_rect(fill=background_colour),
    strip.text = ggplot2::element_text(colour = text_colour, face = "bold",
                                       size = ggplot2::rel(1)),
    panel.border = ggplot2::element_blank()
  )
}

showtext::showtext_auto()
# showtext::showtext_auto(FALSE)

p + 
  labs(title = "title",
       subtitle = "subtitle",
       caption = "caption") +
  explanatory_theme_1(base_text_size = 10)

showtext::showtext_auto(FALSE)

ggsave("plot.svg")

```
```{r fig.asp = 0.8, fig.width = 5, out.width = "100%"}
explanatory_theme_2 <- function(){
  
  
  grid_line_colour <- "grey"
  text_colour <- "black"
  background_colour <- "grey98"
  
  
  ggplot2::theme_bw() %+replace%
  
  ggplot2::theme(
    
    # format text
    text = ggplot2::element_text(family = "Lato", size = 10),
    plot.title = ggplot2::element_text(hjust = 0,size = 16),
    plot.subtitle = ggplot2::element_text(hjust = 0, size = 12),
    plot.caption = ggplot2::element_text(size = 8, 
                                         hjust = 0),
    
    # format legend
    legend.position = "top",
    legend.background = ggplot2::element_blank(),
    legend.title = ggplot2::element_blank(),
    legend.text = ggplot2::element_text(size = 10),
    
    # format axis
    axis.text = ggplot2::element_text(face = "bold"),
    axis.title.x = ggplot2::element_text(),
    axis.title.y = ggplot2::element_blank(),
    axis.line.y = ggplot2::element_blank(),
    axis.line.x = ggplot2::element_blank(),
    # axis.line.x = ggplot2::element_line(colour = "black", size = 1),
    axis.ticks.x = ggplot2::element_line(colour = grid_line_colour, size = 1),
    axis.ticks.y = ggplot2::element_blank(),
    axis.text.x = ggplot2::element_text(margin=ggplot2::margin(t = 1, b = 10)),
    
    # format plot gridlines
    panel.grid.minor = ggplot2::element_blank(),
    panel.grid.major.x = ggplot2::element_blank(),
    panel.grid.major.y = ggplot2::element_line(colour = grid_line_colour),
    
    # format plot background
    panel.background = ggplot2::element_blank(),
    
    # format overall background (i.e. background behind the entire figure
    # including the plot, titles etc.)
    plot.background = element_rect(fill = background_colour,
                                   colour = NA),
    
    # facet labels background
    strip.background = ggplot2::element_rect(fill=background_colour),
    strip.text = ggplot2::element_text(colour = text_colour, face = "bold",
                                       size = 12),
    panel.border = ggplot2::element_blank()
  )
}

showtext::showtext_auto()
# showtext::showtext_auto(FALSE)

p + 
  labs(title = "title",
       subtitle = "subtitle",
       caption = "caption") +
  explanatory_theme_2()

showtext::showtext_auto(FALSE)

ggsave("plot.svg")

```

